# Generated by Django 5.1.7 on 2025-07-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigiKeyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('quantity_available', models.IntegerField()),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('raw_data', models.JSONField()),
            ],
        ),
    ]
