# Generated by Django 5.1.7 on 2025-07-31 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('category_id', 'level')},
            },
        ),
        migrations.CreateModel(
            name='DJManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DJPackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DJParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_text', models.CharField(max_length=255)),
                ('parameter_type', models.CharField(max_length=50)),
                ('value_text', models.CharField(max_length=255)),
                ('value_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DJProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_product_number', models.CharField(max_length=100, unique=True)),
                ('product_description', models.CharField(max_length=255)),
                ('detailed_description', models.TextField()),
                ('quantity_available', models.IntegerField()),
                ('product_url', models.URLField()),
                ('is_discontinued', models.BooleanField()),
                ('normally_stocking', models.BooleanField()),
                ('is_obsolete', models.BooleanField()),
                ('manufacturer_lead_weeks', models.CharField(blank=True, max_length=10, null=True)),
                ('manufacturer_public_quantity', models.IntegerField()),
                ('standard_package', models.IntegerField()),
                ('export_control_class_number', models.CharField(blank=True, max_length=20, null=True)),
                ('htsus_code', models.CharField(blank=True, max_length=20, null=True)),
                ('moisture_sensitivity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('is_bo_not_allowed', models.BooleanField()),
                ('is_ncnr', models.BooleanField()),
                ('contains_lithium', models.BooleanField()),
                ('contains_mercury', models.BooleanField()),
                ('is_end_of_life', models.BooleanField()),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='vendorapi.djcategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorapi.djmanufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='DJProductOtherName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_names', to='vendorapi.djproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DJProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DJProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digikey_product_number', models.CharField(max_length=100, unique=True)),
                ('quantity_available_for_package_type', models.IntegerField()),
                ('minimum_order_quantity', models.IntegerField()),
                ('max_quantity_for_distribution', models.IntegerField(blank=True, null=True)),
                ('marketplace', models.BooleanField()),
                ('is_tariff_active', models.BooleanField()),
                ('digireeling_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendorapi.djpackagetype')),
            ],
        ),
        migrations.CreateModel(
            name='DJStandardPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.DeleteModel(
            name='DigiKeyProduct',
        ),
        migrations.AddField(
            model_name='djparameter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorapi.djproduct'),
        ),
        migrations.AddField(
            model_name='djproduct',
            name='product_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendorapi.djproductstatus'),
        ),
        migrations.AddField(
            model_name='djproductvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='vendorapi.djproduct'),
        ),
        migrations.AddField(
            model_name='djstandardpricing',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_pricing', to='vendorapi.djproductvariation'),
        ),
    ]
