# Generated by Django 5.1.7 on 2025-07-31 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0002_djcategory_djmanufacturer_djpackagetype_djparameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='djcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendorapi.djcategory'),
        ),
        migrations.AddField(
            model_name='djproduct',
            name='datasheet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djproduct',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
