# Generated by Django 5.1.7 on 2025-07-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0003_djcategory_parent_djproduct_datasheet_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djproduct',
            name='standard_package',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
