# Generated by Django 5.1.7 on 2025-07-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0004_alter_djproduct_standard_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djproduct',
            name='contains_lithium',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='contains_mercury',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='is_bo_not_allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='is_discontinued',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='is_end_of_life',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='is_ncnr',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='is_obsolete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='normally_stocking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='product_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='djproduct',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
