# Generated by Django 5.1.7 on 2025-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0005_alter_djproduct_contains_lithium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djparameter',
            name='value_id',
            field=models.CharField(max_length=255),
        ),
    ]
