# Generated by Django 5.1.7 on 2025-09-10 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapi', '0006_alter_djparameter_value_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_pn', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_parts', to='vendorapi.djproduct')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendorapi.vendor')),
            ],
            options={
                'unique_together': {('product', 'vendor')},
            },
        ),
    ]
