tunnel: ecommerce-tunnel
credentials-file: /home/pi/.cloudflared/ecommerce-tunnel.json

ingress:
  - hostname: ecommerce.cameron-dietz.com
    service: http://next:3000

  - hostname: api.cameron-dietz.com
    service: http://django:8000

  - hostname: service.cameron-dietz.com
    service: http://node-service:4000

  - service: http_status:404
