tunnel: ecommerce-tunnel
credentials-file: /home/pi/.cloudflared/ecommerce-tunnel.json

ingress:
  - hostname: ecommerce.cameron-dietz.com
    service: http://localhost:3000

  - hostname: api.cameron-dietz.com
    service: http://localhost:8000

  - hostname: service.cameron-dietz.com
    service: http://localhost:4000

  - service: http_status:404
