version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    networks:
      - ecommerce

  backend:
    build: ./backend
    container_name: django-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    #depends_on:
      #- db
    networks:
      - ecommerce

  search:
    build: ./node-service
    container_name: node-express-service
    ports:
      - "4000:4000"
    networks:
      - ecommerce

networks:
  ecommerce:


