# Generated by Django 5.1.7 on 2025-07-23 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_order_stripe_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtimClass',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtimFeature',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtimFeatureGroup',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtimGroup',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtimUnit',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtimValue',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EtimClassFeatureMap',
            fields=[
                ('artclassfeaturenr', models.BigIntegerField(primary_key=True, serialize=False)),
                ('feature_type', models.CharField(choices=[('A', 'Alphanumeric'), ('N', 'Numeric'), ('F', 'Float'), ('B', 'Boolean'), ('E', 'Enumeration')], max_length=1)),
                ('sort_number', models.PositiveIntegerField(blank=True, null=True)),
                ('etim_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.etimclass')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.etimfeature')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.etimunit')),
            ],
            options={
                'unique_together': {('etim_class', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='EtimClassSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255)),
                ('etim_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.etimclass')),
            ],
        ),
        migrations.AddField(
            model_name='etimfeature',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.etimfeaturegroup'),
        ),
        migrations.AddField(
            model_name='etimclass',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='apiapp.etimgroup'),
        ),
        migrations.CreateModel(
            name='EtimClassFeatureValueMap',
            fields=[
                ('artclassfeaturevaluenr', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sort_number', models.PositiveIntegerField(blank=True, null=True)),
                ('feature_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_maps', to='apiapp.etimclassfeaturemap')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.etimvalue')),
            ],
            options={
                'unique_together': {('feature_map', 'value')},
            },
        ),
    ]
