# Generated by Django 5.1.7 on 2025-07-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_etimclass_etimfeature_etimfeaturegroup_etimgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etimclass',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='etimclass',
            name='version_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
