# Generated by Django 5.1.7 on 2025-07-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_etimclass_version_etimclass_version_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etimclass',
            name='code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etimclass',
            name='version',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='etimclass',
            name='version_date',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='etimfeature',
            name='code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etimfeaturegroup',
            name='code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etimunit',
            name='code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etimunit',
            name='symbol',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='etimvalue',
            name='code',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
