# Generated by Django 5.1.7 on 2025-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_alter_etimclass_code_alter_etimclass_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
