# Generated by Django 5.1.7 on 2025-07-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etimclassfeaturemap',
            name='feature_type',
            field=models.CharField(choices=[('A', 'Alphanumeric'), ('N', 'Numeric'), ('F', 'Float'), ('B', 'Boolean'), ('E', 'Enumeration')], max_length=15),
        ),
    ]
