# Generated by Django 5.1.7 on 2025-07-25 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0010_alter_etimclassfeaturemap_feature_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etimunit',
            name='name',
        ),
    ]
