# Generated by Django 5.1.7 on 2025-08-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_remove_etimunit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_visible',
            field=models.BinaryField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_street2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_auto',
            field=models.BinaryField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BinaryField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
