# Generated by Django 5.1.7 on 2025-09-08 02:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_categoryattribute_homepageconfig_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageconfig',
            name='featured_manufacturer_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
