# Generated by Django 5.1.7 on 2025-09-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_homepageconfig_featured_manufacturer_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturer_images/'),
        ),
    ]
