# Generated by Django 5.1.7 on 2025-09-10 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0015_manufacturer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_until', models.DateTimeField()),
                ('method', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_automatic', models.BooleanField(default=False)),
                ('custom_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_discountable', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='apiapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'valid_until'], name='apiapp_prod_product_8c6519_idx')],
            },
        ),
    ]
