# Generated by Django 5.1.7 on 2025-09-10 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_alter_productprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='apiapp.product'),
        ),
        migrations.CreateModel(
            name='testtemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_automatic', models.BooleanField(blank=True, default=False, null=True)),
                ('custom_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_discountable', models.BooleanField(blank=True, default=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricedata', to='apiapp.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'valid_until'], name='apiapp_test_product_5fd938_idx')],
            },
        ),
    ]
