# Generated by Django 5.1.7 on 2025-09-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_alter_productprice_product_testtemp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testtemp',
        ),
    ]
