# Generated by Django 5.1.7 on 2025-09-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0021_delete_testtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='Weight in Lbs', null=True),
        ),
    ]
