# Generated by Django 5.1.7 on 2025-09-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0023_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='apiapp_prod_name_461daa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='apiapp_prod_categor_6824dc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_visible'], name='apiapp_prod_is_visi_3cee1e_idx'),
        ),
    ]
